apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: back-app
  name: back-app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: back-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: back-app
    spec:
      containers:
        - env:
            - name: MONGO_DB_URL
              value: mongodb://nodejs-kubernetes-mongodb:27017/nodejs-kubernetes
            - name: PORT
              value: "80"
            - name: HOST_IP
              value: "10.105.98.181"
            - name: HOST_PORT
              value: "8099"
            - name: MONGO_DB_IP
              value: "10.99.247.97"
            - name: MONGO_DB_PORT
              value: "27017"
          image: dealltest/backapp:v1
          name: back-app-v1
          #imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
