apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: back-app
  name: back-app-v1
spec:
  type: LoadBalancer
  ports:
    - name: "8099"
      port: 8099
      targetPort: 8099
  selector:
    io.kompose.service: back-app
status:
  loadBalancer: {}
